# Generated by Django 4.2.11 on 2024-03-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_alter_employee_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RemoveField(
            model_name='contactinformation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='document',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='employee',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='ContactInformation',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
