# Generated by Django 4.2.11 on 2024-03-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_employee_age_alter_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
